# permissions for end users to edit ptphaconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptphaconfig-editor-role
rules:
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptphaconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptphaconfigs/status
  verbs:
  - get
